//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAEntitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_ASSIGNMENT
    {
        public string KEYED_NAME { get; set; }
        public string CLASSIFICATION { get; set; }
        public string ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public string CREATED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string STATE { get; set; }
        public string CURRENT_STATE { get; set; }
        public string IS_CURRENT { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string MINOR_REV { get; set; }
        public string MAJOR_REV { get; set; }
        public string IS_RELEASED { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string RELATED_ID { get; set; }
        public string SOURCE_ID { get; set; }
        public Nullable<int> SORT_ORDER { get; set; }
        public string BEHAVIOR { get; set; }
        public string TEAM_ID { get; set; }
        public string CSS { get; set; }
        public string CLAIMED_BY { get; set; }
        public string CLOSED_BY { get; set; }
        public Nullable<System.DateTime> CLOSED_ON { get; set; }
        public string COMMENTS { get; set; }
        public string ESCALATE_TO { get; set; }
        public string FOR_ALL_MEMBERS { get; set; }
        public string IS_DISABLED { get; set; }
        public string IS_OVERDUE { get; set; }
        public string IS_REQUIRED { get; set; }
        public string PATH { get; set; }
        public Nullable<int> REMINDERS_SENT { get; set; }
        public int VOTING_WEIGHT { get; set; }
        public string CONFIG_ID { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public string NEW_VERSION { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string PERMISSION_ID { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        public virtual IDENTITY IDENTITY { get; set; }
    }
}
