//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAEntitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_BUSINESSTRAVEL
    {
        public string id { get; set; }
        public string CLASSIFICATION { get; set; }
        public string KEYED_NAME { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY_ID { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public string CURRENT_STATE { get; set; }
        public string STATE { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string IS_CURRENT { get; set; }
        public string MAJOR_REV { get; set; }
        public string MINOR_REV { get; set; }
        public string IS_RELEASED { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string CSS { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string NEW_VERSION { get; set; }
        public string CONFIG_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string TEAM_ID { get; set; }
        public string B_COMPANYCODE { get; set; }
        public string B_LOCATION { get; set; }
        public Nullable<System.DateTime> B_APPLICATIONDATE { get; set; }
        public string B_TRIPTYPE { get; set; }
        public string B_TYPE { get; set; }
        public string B_PREPARER { get; set; }
        public string B_EMPLOYEE { get; set; }
        public string B_STAFFNO { get; set; }
        public string B_POSITION { get; set; }
        public string B_DEPT { get; set; }
        public string B_COSTCENTER { get; set; }
        public string B_MOBILE { get; set; }
        public string B_PROJECTNAME { get; set; }
        public string B_DESTINATION { get; set; }
        public string B_SENIORMANAGER { get; set; }
        public string B_DIRECTOR { get; set; }
        public string B_VP { get; set; }
        public Nullable<System.DateTime> B_TRAVELDATE { get; set; }
        public Nullable<System.DateTime> B_ESTIMATEDRETURNDATE { get; set; }
        public string B_PURPOSE { get; set; }
        public string B_TRAVELSCHEDULE { get; set; }
        public Nullable<decimal> B_TRAVELBUDGET { get; set; }
        public string B_DOCUMENTNO { get; set; }
        public string B_REMARK { get; set; }
        public Nullable<int> B_INDEXNUM { get; set; }
        public string B_ISHANGUP { get; set; }
        public string B_HANGUPACTIVITYNAME { get; set; }
        public string B_FLIGHTISSSUE { get; set; }
        public string B_FLIGHTBOOKING { get; set; }
        public string B_HOTELBOOKING { get; set; }
        public string B_DIDI { get; set; }
        public string B_OTHERS { get; set; }
        public string B_NEEDADMINSUPPORT { get; set; }
        public string B_OTHERCONTENT { get; set; }
        public string B_VERSIONNO { get; set; }
        public Nullable<decimal> B_TRAFFICEXPENSE { get; set; }
        public Nullable<decimal> B_HOTELEXPENSE { get; set; }
        public Nullable<decimal> B_FIXEDSUBSIDY { get; set; }
        public Nullable<decimal> B_OTHEREXPENSES { get; set; }
        public Nullable<int> B_ISREIMBURSEMENT { get; set; }
        public Nullable<decimal> B_DIDIMONEY { get; set; }
        public Nullable<decimal> B_DIDIADDMONEY { get; set; }
    }
}
