//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAEntitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_ISSUEMANAGE
    {
        public string id { get; set; }
        public string CLASSIFICATION { get; set; }
        public string KEYED_NAME { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY_ID { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public string CURRENT_STATE { get; set; }
        public string STATE { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string IS_CURRENT { get; set; }
        public string MAJOR_REV { get; set; }
        public string MINOR_REV { get; set; }
        public string IS_RELEASED { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string CSS { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string NEW_VERSION { get; set; }
        public string CONFIG_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string TEAM_ID { get; set; }
        public string B_CCC { get; set; }
        public string B_CHOICEWORKFLOW { get; set; }
        public string B_CONTACTINFORMATION { get; set; }
        public string B_DATAVERSION { get; set; }
        public Nullable<System.DateTime> B_ENTRYDATE { get; set; }
        public string B_FREQUENCY { get; set; }
        public string B_ISNEWQUESTION { get; set; }
        public string B_ISSUECODE { get; set; }
        public string B_ISSUETITLE { get; set; }
        public string B_LEADMAN { get; set; }
        public string B_LEADUNIT { get; set; }
        public Nullable<System.DateTime> B_OCCURRENCEDATE { get; set; }
        public string B_PARTATTRIBUTE { get; set; }
        public string B_PARTNAME { get; set; }
        public string B_PARTNUMBER { get; set; }
        public Nullable<System.DateTime> B_PHASEUPDATETIME { get; set; }
        public string B_PICTURE { get; set; }
        public string B_PRELIMINARYANALYSIS { get; set; }
        public string B_PRELIMINARYCOUNTERMEASURES { get; set; }
        public string B_PRESENTPEOPLE { get; set; }
        public string B_PROBLEMDESCRIPTION { get; set; }
        public string B_PROBLEMPHASE { get; set; }
        public string B_PROBLEMPROPERTIES { get; set; }
        public string B_PROBLEMSOURCE { get; set; }
        public string B_PRODUCTSEQUENCE { get; set; }
        public string B_PROJECTCODE { get; set; }
        public string B_PROPOSEUNIT { get; set; }
        public string B_QUALITYMANAGER { get; set; }
        public string B_QUALITYOFFICER { get; set; }
        public string B_RECOMMENDEDMEASURE { get; set; }
        public Nullable<System.DateTime> B_REQUIREDCOMPLETIONTIME { get; set; }
        public Nullable<int> B_RUNNINGMILEAGE { get; set; }
        public string B_RUNTIME { get; set; }
        public string B_SAMPLE { get; set; }
        public string B_SEVERITY { get; set; }
        public string B_SUBORDINATESYSTEM { get; set; }
        public string B_SUPERVISOR { get; set; }
        public string B_VFGF { get; set; }
        public string B_WORKFLOWSTAGE { get; set; }
    }
}
