//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAEntitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_PRMANAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B_PRMANAGE()
        {
            this.B_CHOICESUPPLIERS = new HashSet<B_CHOICESUPPLIERS>();
        }
    
        public string id { get; set; }
        public string CLASSIFICATION { get; set; }
        public string KEYED_NAME { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY_ID { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public string CURRENT_STATE { get; set; }
        public string STATE { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string IS_CURRENT { get; set; }
        public string MAJOR_REV { get; set; }
        public string MINOR_REV { get; set; }
        public string IS_RELEASED { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string CSS { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string NEW_VERSION { get; set; }
        public string CONFIG_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string TEAM_ID { get; set; }
        public string B_APPLICANT { get; set; }
        public string B_APPLICANTID { get; set; }
        public string B_AUTHORIZEDPURCHASE { get; set; }
        public decimal B_BUDGET { get; set; }
        public string B_BUDGETCODE { get; set; }
        public string B_BUDGETSTATUS { get; set; }
        public string B_BUSINESSDEPARTMENT { get; set; }
        public string B_BUYER { get; set; }
        public string B_BUYERID { get; set; }
        public string B_EMAILADDRESS { get; set; }
        public int B_INDEXNUM { get; set; }
        public string B_PHONENO { get; set; }
        public string B_PROJECTDIRECTOR { get; set; }
        public string B_PROJECTLEADER { get; set; }
        public string B_PROJECTNAME { get; set; }
        public string B_PRRECORDNO { get; set; }
        public string B_PRTYPE { get; set; }
        public System.DateTime B_RAISEDDATE { get; set; }
        public string B_REPETITIVEPURCHASE { get; set; }
        public string B_URGENTPURCHASE { get; set; }
        public string B_PURCHASECONTENT { get; set; }
        public string B_CONTRACTPARTY { get; set; }
        public string B_APPLICANTADDRESS { get; set; }
        public string B_ISSINGLESUPPLIER { get; set; }
        public string B_CONTRACTTYPE { get; set; }
        public string B_DEPTMANAGER { get; set; }
        public string B_DEPTDIRECTOR { get; set; }
        public Nullable<decimal> B_ADDITIONALBUDGET { get; set; }
        public string B_COSTCENTER { get; set; }
        public string B_PURCHASINGREASON { get; set; }
        public string B_PROJECTMANAGER { get; set; }
        public string B_REMARK { get; set; }
        public string B_VERSIONNO { get; set; }
        public string B_DEPTVP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_CHOICESUPPLIERS> B_CHOICESUPPLIERS { get; set; }
    }
}
