//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAEntitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_TRIPREIMBURSEMENTFORM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B_TRIPREIMBURSEMENTFORM()
        {
            this.R_HOTELEXPENSE = new HashSet<R_HOTELEXPENSE>();
            this.R_MEALSANDFIXEDSUBSIDIES = new HashSet<R_MEALSANDFIXEDSUBSIDIES>();
            this.R_TRAFFICEXPENSE = new HashSet<R_TRAFFICEXPENSE>();
            this.R_OTHERS = new HashSet<R_OTHERS>();
        }
    
        public string id { get; set; }
        public string CLASSIFICATION { get; set; }
        public string KEYED_NAME { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY_ID { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public string CURRENT_STATE { get; set; }
        public string STATE { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string IS_CURRENT { get; set; }
        public string MAJOR_REV { get; set; }
        public string MINOR_REV { get; set; }
        public string IS_RELEASED { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string CSS { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string NEW_VERSION { get; set; }
        public string CONFIG_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string TEAM_ID { get; set; }
        public string B_RECORDNO { get; set; }
        public string B_COMPANYCODE { get; set; }
        public string B_REIMBURSEMENTPLACE { get; set; }
        public string B_ISBUDGETARY { get; set; }
        public Nullable<System.DateTime> B_APPLICATIONDATE { get; set; }
        public string B_INTALBUSINESS { get; set; }
        public string B_PREPARER { get; set; }
        public string B_PREPARERNO { get; set; }
        public string B_EMPLOYEE { get; set; }
        public string B_STAFFNO { get; set; }
        public string B_POSITION { get; set; }
        public string B_DEPT { get; set; }
        public string B_COSTCENTER { get; set; }
        public string B_TEL { get; set; }
        public string B_BUDGETNUMBER { get; set; }
        public Nullable<decimal> B_ADVANCEDAMOUNT { get; set; }
        public Nullable<decimal> B_TOTALEXPENSE { get; set; }
        public Nullable<int> B_INDEXNUM { get; set; }
        public string B_TYPE { get; set; }
        public string B_DEPTLEADER { get; set; }
        public string B_LINELEADER { get; set; }
        public string B_DIVISIONVP { get; set; }
        public Nullable<int> B_ATTACHMENTSQUANTITY { get; set; }
        public string B_LINELEADERID { get; set; }
        public string B_DEPTLEADERID { get; set; }
        public string B_DIVISIONVPID { get; set; }
        public string B_REMARK { get; set; }
        public string B_ISHANGUP { get; set; }
        public string B_AMOUNTINWORDS { get; set; }
        public Nullable<decimal> B_TOTALAMOUNT { get; set; }
        public string B_HANGUPACTIVITYNAME { get; set; }
        public string B_ISSENDTOSAP { get; set; }
        public string B_ACCOUNT_DOC { get; set; }
        public string B_EACDATE { get; set; }
        public string B_HOTELINWORDS { get; set; }
        public Nullable<decimal> B_HOTELAMOUNT { get; set; }
        public string B_TRAFINWORDS { get; set; }
        public Nullable<decimal> B_TRAFAMOUNT { get; set; }
        public string B_MEALINWORDS { get; set; }
        public Nullable<decimal> B_MEALAMOUNT { get; set; }
        public string B_OTHINWORDS { get; set; }
        public Nullable<decimal> B_OTHAMOUNT { get; set; }
        public string B_AMOUNTINTOTAL { get; set; }
        public string B_BTRECORDNO { get; set; }
        public Nullable<decimal> B_TRAVELBUDGET { get; set; }
        public string B_ISBEYONDBUDGET { get; set; }
        public string B_BEYONDREASON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_HOTELEXPENSE> R_HOTELEXPENSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_MEALSANDFIXEDSUBSIDIES> R_MEALSANDFIXEDSUBSIDIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_TRAFFICEXPENSE> R_TRAFFICEXPENSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_OTHERS> R_OTHERS { get; set; }
    }
}
