//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAEntitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string KEYED_NAME { get; set; }
        public string TEAM_ID { get; set; }
        public string CLASSIFICATION { get; set; }
        public string CELL { get; set; }
        public string COMPANY_NAME { get; set; }
        public string DEFAULT_VAULT { get; set; }
        public string EMAIL { get; set; }
        public string ESIGNATURE { get; set; }
        public string FAX { get; set; }
        public string FIRST_NAME { get; set; }
        public string HOME_PHONE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_DATE { get; set; }
        public string LABEL { get; set; }
        public string LAST_NAME { get; set; }
        public string LOGON_ENABLED { get; set; }
        public string MAIL_STOP { get; set; }
        public string MANAGER { get; set; }
        public string PAGER { get; set; }
        public string PASSWORD { get; set; }
        public string PICTURE { get; set; }
        public Nullable<System.DateTime> PWD_IS_SET_ON { get; set; }
        public string STARTING_PAGE { get; set; }
        public string TELEPHONE { get; set; }
        public string USER_NO { get; set; }
        public string WORKING_DIRECTORY { get; set; }
        public string LOGIN_NAME { get; set; }
        public string CONFIG_ID { get; set; }
        public string CREATED_BY_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CSS { get; set; }
        public string CURRENT_STATE { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string ID { get; set; }
        public string IS_CURRENT { get; set; }
        public string IS_RELEASED { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string MAJOR_REV { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public string MINOR_REV { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string NEW_VERSION { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string STATE { get; set; }
        public string B_JOBNUMBER { get; set; }
        public string B_CHINESENAME { get; set; }
        public string B_ENGLISHNAME { get; set; }
        public string B_CENTRE { get; set; }
        public string B_DEPARTMENT { get; set; }
        public string B_IDNUMBER { get; set; }
        public string B_SENIORMANAGER { get; set; }
        public string B_DIRECTOR { get; set; }
        public string B_VP { get; set; }
        public string B_AFFILIATEDCOMPANY { get; set; }
    }
}
