//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAEntitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_MAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKFLOW_MAP()
        {
            this.WORKFLOW_MAP_ACTIVITY = new HashSet<WORKFLOW_MAP_ACTIVITY>();
        }
    
        public string ARAS_UNIQUENESS_HELPER { get; set; }
        public string CONFIG_ID { get; set; }
        public string NEW_VERSION { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public string TEAM_ID { get; set; }
        public string CLASSIFICATION { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string COMMENTS { get; set; }
        public string DESCRIPTION { get; set; }
        public string LABEL { get; set; }
        public string NODE_BG_COLOR { get; set; }
        public string NODE_LABEL1_COLOR { get; set; }
        public string NODE_LABEL1_FONT { get; set; }
        public string NODE_LABEL2_COLOR { get; set; }
        public string NODE_LABEL2_FONT { get; set; }
        public string NODE_NAME_COLOR { get; set; }
        public string NODE_NAME_FONT { get; set; }
        public string NODE_SIZE { get; set; }
        public string PROCESS_OWNER { get; set; }
        public string TRANSITION_LINE_COLOR { get; set; }
        public string TRANSITION_NAME_COLOR { get; set; }
        public string TRANSITION_NAME_FONT { get; set; }
        public string NAME { get; set; }
        public string CREATED_BY_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CSS { get; set; }
        public string CURRENT_STATE { get; set; }
        public string ID { get; set; }
        public string IS_CURRENT { get; set; }
        public string IS_RELEASED { get; set; }
        public string KEYED_NAME { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string MAJOR_REV { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public string MINOR_REV { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string STATE { get; set; }
        public Nullable<System.DateTime> SUPERSEDED_DATE { get; set; }
        public string LABEL_ZC1 { get; set; }
        public string DESCRIPTION_ZC1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKFLOW_MAP_ACTIVITY> WORKFLOW_MAP_ACTIVITY { get; set; }
    }
}
